### PR TITLE
Add docs for lab maintenance and daily activities

### PR DESCRIPTION
**Pull request by ryisenberg**
https://github.com/ryisenberg/protocols/blob/patch-2/README.md#lab-maintenece
https://github.com/ryisenberg/protocols/blob/patch-2/README.md#equipment

Not sure if I added these links the way you wanted me to...

### CODE REVIEW

**Comment by mandel01** [comment]
I’m confused - where are those links? The ones in the README.md (to each individual page) look good.


On Feb 15, 2018, at 3:02 PM, Ruth Isenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


https://github.com/ryisenberg/protocols/blob/patch-2/README.md#lab-maintenece
https://github.com/ryisenberg/protocols/blob/patch-2/README.md#equipment

Not sure if I added these links the way you wanted me to...

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/mjmlab/protocols/pull/27

Commit Summary

  *   Add making media protocol
  *   Add link to making media
  *   Create preparing-sterile-lab-supplies.md
  *   Create shelf-stocking-protocol.md
  *   Add protocols

File Changes

  *   M README.md<https://github.com/mjmlab/protocols/pull/27/files#diff-0> (6)
  *   M media.md<https://github.com/mjmlab/protocols/pull/27/files#diff-1> (56)
  *   A preparing-sterile-lab-supplies.md<https://github.com/mjmlab/protocols/pull/27/files#diff-2> (75)
  *   A shelf-stocking-protocol.md<https://github.com/mjmlab/protocols/pull/27/files#diff-3> (6)

Patch Links:

  *   https://github.com/mjmlab/protocols/pull/27.patch
  *   https://github.com/mjmlab/protocols/pull/27.diff

**Comment by ryisenberg** [comment]
Oh wait, never mind. I misunderstood what you said in the earlier message, but I get it now.

Thanks!

Ruth

------------------------------------------------------
Ruth Isenberg
PhD Student, Mark Mandel lab
Microbiology Doctoral Training Program
University of Wisconsin-Madison
University of Puget Sound alumna
risenberg@wisc.edu<mailto:risenberg@wisc.edu>
ruth.yi.isenberg@gmail.com

On Feb 15, 2018, at 3:25 PM, Mark Mandel <notifications@github.com<mailto:notifications@github.com>> wrote:

I’m confused - where are those links? The ones in the README.md (to each individual page) look good.


On Feb 15, 2018, at 3:02 PM, Ruth Isenberg <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


https://github.com/ryisenberg/protocols/blob/patch-2/README.md#lab-maintenece
https://github.com/ryisenberg/protocols/blob/patch-2/README.md#equipment

Not sure if I added these links the way you wanted me to...

________________________________
You can view, comment on, or merge this pull request online at:

https://github.com/mjmlab/protocols/pull/27

Commit Summary

* Add making media protocol
* Add link to making media
* Create preparing-sterile-lab-supplies.md
* Create shelf-stocking-protocol.md
* Add protocols

File Changes

* M README.md<https://github.com/mjmlab/protocols/pull/27/files#diff-0> (6)
* M media.md<https://github.com/mjmlab/protocols/pull/27/files#diff-1> (56)
* A preparing-sterile-lab-supplies.md<https://github.com/mjmlab/protocols/pull/27/files#diff-2> (75)
* A shelf-stocking-protocol.md<https://github.com/mjmlab/protocols/pull/27/files#diff-3> (6)

Patch Links:

* https://github.com/mjmlab/protocols/pull/27.patch
* https://github.com/mjmlab/protocols/pull/27.diff

**Comment by ryisenberg** [comment]
Hi Mark, 

When you get a chance could you merge the pull requests, please? Unless there's something wrong with my branch, of course.

Ruth

**Comment by mandel01** [comment]
I merged them. I was confused about the exchange above and thought we were still waiting on something. Should be good!

**Comment by ryisenberg** [comment]
Ah okay, I should have clarified better earlier, but everything is good. Thank you!

**Pull request merged**
