### PR TITLE
Updating protocols for Student Hourlies and future lab members

### PR DESCRIPTION
**Pull request by Holschbachc**
Updating documentation for student hourlies

### CODE REVIEW

**Comment by mandel01** [comment]
I'm working on updating some language here with @Holschbachc now.

Later I'll ask @JakeVanderGriend to add info on the right Lanceraid too.

**Comment by JakeVanderGriend** [comment]
I would recommend that the reloading acid/detergent instructions mention getting a grad student/post-doc if they're doing it for the first time. The tubes that connect the machine to the bottles can snap if handled roughly since they're older tubing, and fitting the bottles back in takes a little finagling. 

Acid we need:     LANCER USA INC LancerAcid Rinse, LCA-A, 2×2.5 gal (NC9991290)

Citric acid isn't strong enough for Madison water, we have to use LCA-Acetic.

**Comment by dlmiller22** [comment]
It looks good to me-- maybe we could add the comment about "if you're doing it the first time ask someone to show you" to the front of the handbook too. There's some things Drew and Ander have not done yet i.e. racking tips, making xgal etc.

**Comment by mandel01** [comment]
Let's also wordsmith the tris-buffer.md in the future.

**Pull request merged**
