### PR TITLE
Update gene-deletion.md

### PR DESCRIPTION
**Pull request by ellarotman**
Update protocol to include screen on intermediate cam concentration.

### CODE REVIEW

**Comment by mandel01** [comment]
Hi @ellarotman, great to see this proposed change! Here are my comments. I think you said you had some of these already. Let me know if you need help making the changes here.

line 7 “resistastance”

In line 16 “(suggested concentration 1 - 2.5 μg/ml)”, what actual concentration do you use? Why is there a range here? Can you provide more specifics?

Line 22 “Note that you can streak >1 colony per plate” - how many is ideal?

Line 22 “Incubate overnight at 25-28°C” What temperature do you use? Do both work or are you assuming here?

Line 24 - should this be 8 per plate plus parent OR parent + 7 per plate? Is this theantibiotic-sensitive parent strain? If so can that be stated?

Line 26 - clarify wording of “have one uniformly large size of colonies”

Line 32 “ioculate”

Line 38 “1:100 or 1:1000” - which one do you use? How long should they grow until the specified OD?

Line 44 “Patch ~80 -100 single colonies” - can this be written more clearly? “Patch approximately 100 colonies?

**Comment by mandel01** [comment]
Also, as you go through the deletion-making with @Hauserman2017 both of you can give some thought to what other steps we need documentation - overall concept, Gibson assembly approach, etc.

**Comment by mandel01** [comment]
@ellarotman Can you please finish this today? Hector is about to jump into deletions.

**Comment by ellarotman** [comment]
Update protocol by clarifying text and fixing typos.

**Comment by ellarotman** [comment]
Update protocol by clarifying text and fixing typos.

**Pull request merged**
