### PR TITLE
Edits to media and supplies protocols

### PR DESCRIPTION
**Pull request by ryisenberg**

### CODE REVIEW

**Comment by mandel01** [comment]
@ryisenberg Also I don't think it's a good idea to have the antibiotic info in two separate files. It's a recipe for one of them to get updated and not the future. Can we find one place for this info? Can get rid of the old file if you want it moved into a different one.

**Comment by ryisenberg** [comment]
I saw them but I'm not sure what they mean or how to fix them. And I can get rid of the antibiotics table in the hourlies repo and put in a link to it.

**Comment by mandel01** [comment]
We can chat this afternoon.







On Apr 9, 2018, at 11:49 AM, Ruth Isenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


I saw them but I'm not sure what they mean or how to fix them. And I can get rid of the antibiotics table in the hourlies repo and put in a link to it.

**Comment by mandel01** [comment]
Also `dishwasher` needs to become `dishwasher.md`. Can do this in person later too.

**Comment by mandel01** [comment]
Update media and autoclave files

**Pull request merged**
